name: Continous integration
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn && yarn install
      - name: Run jest tests
        run: yarn test
